#arithemetic
print(5%2)
print(5+4)
print(10/5)
print(2*6)
#comparison
print(5>4)
print(6<7)
print(5==5)
print(6<=7)
print(6!=4)
print(4-6)
#logical
print(True and True)
print(True and False)
print(False and False)
print(True or False)
print(True or True)
print(False or False)

print(3>0 or 5>9)
print(3==5 and 5<7)
print(8<2 or 0<=5)
print("apple" + "juice")
print("ant" > "penguin")
print("elephant" > "penguin")
print("whale" > "ant")
print("penguin" < "elephant")
print("whale" > "penguin")
print("elephant" > "ant")
print("elephant" > "Penguin")
print(2+2*2)
print((2+2)*2)
print((4+(3-7)*5)/2  -7)
print()
